### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by paulusm** [patrickkfkan/volumio-mixcloud#3]
Is this due to a change to the Mixcloud site? I just get blank pages

**Comment by patrickkfkan** [comment]
Should have been fixed in v0.1.3. Did you install it from the beta channel of plugin store?

- Uninstall current version.
- Enable Plugins Test Mode in `http://<volumio address>/dev`
- Find the Mixcloud plugin in the plugin store. Click the Details button under it and choose latest beta version to install.
- Restart Volumio.

**Comment by paulusm** [comment]
Yes! back in business. Thanks very much for the swift response - love this plugin, much appreciated!
